### PR TITLE
Update table of releases

### PR DESCRIPTION
**Pull request by sjlewis-jpl**
My goal is to make the table with release versions focused on the needs of users, stakeholders, and the public.  The original version of the table was pulled off of our internal wiki page, which contains a lot of information that won't be useful to people outside of the project.  The current version isn't really human-readable due to the limitations of Markdown (forcing narrow table and column widths).

Changes proposed (I'll update this list if any other changes get folded in):
- Reduce the number of columns - keeping 4:  `SDS Release`, `SDS Release Date`, `Product Version`, and `SAS Docker Version`
   - The `SDS Release` version is the same as PCM release versions, so remove those 2 columns.  We could also make that table entry a link to the PCM Release Notes in GitHub.
   - Have the PGE Release versions linked in the PCM Release Notes, thus removing those 2 columns.
   - `SDS Release Date` to reflect when the Release goes live in production (for non-RC releases).  For Release Candidates, capture when it gets delivered to the project (or possibly not track them in these tables).
   - SAS Release Version is an internal versioning scheme used by ADT.  The SAS Versions in documentation and metadata follow the version info in the docker version.  So, just keep the `SAS Docker Version`
- Rename the file from `products.md` to 'releases.md`.
- Rename the page on the website to "Releases", instead of "Products".

Rationale for changing from "Products" to "Releases" - I would expect a "Products" page to have information on the products - identifying them, high-level description of their contents and uses, links to associated docs, and links to the data at the DAACs.  There is already such a page on the OPERA Website.

### CODE REVIEW

**Comment by sjlewis-jpl** [comment]
@riverma - do you know all the files that will need changing if we want to rename this page & table from "Products" to "Releases"?  Seems like a good chance for me to learn the repo's structure and build process.

I know I'll need to change the `products.md` and `intro.md` file.  It looks like there might be stuff in the `src/pages/index.js` file?  Any others?

**Comment by riverma** [comment]
> @riverma - do you know all the files that will need changing if we want to rename this page & table from "Products" to "Releases"? Seems like a good chance for me to learn the repo's structure and build process.
> 
> I know I'll need to change the `products.md` and `intro.md` file. It looks like there might be stuff in the `src/pages/index.js` file? Any others?

@sjlewis-jpl - great question, I can count three locations where `products.md` is referenced:
- https://github.com/nasa-opera/nasa-opera.github.io/blob/update_releases_table/src/pages/index.js#L136
- https://github.com/nasa-opera/nasa-opera.github.io/blob/update_releases_table/src/pages/index.js#L20
- https://github.com/nasa-opera/nasa-opera.github.io/blob/update_releases_table/docs/intro.md?plain=1#L14

One nice thing about Docusaurus is, if you run the `yarn build` command locally, it will report any broken links as a build failure. So there's a good catch-all solution there. I've also installed [a GitHub Action that not only builds and deploys the site](https://github.com/nasa-opera/nasa-opera.github.io/blob/main/.github/workflows/deploy.yml) when you commit to `main` on GitHub.com, but [a GitHub Action that tests out the build](https://github.com/nasa-opera/nasa-opera.github.io/blob/main/.github/workflows/test-deploy.yml) when creating PRs. See the above Check Pass (details [here](https://github.com/nasa-opera/nasa-opera.github.io/actions/runs/10603745247/job/29388779779?pr=1)) - looks like your links are good for now!

Some resources for docusaurus:
- For an overview of Docusaurus: https://docusaurus.io/docs#docusaurus-documentation-made-easy
- For guidance on writing and updating Docs, see: https://docusaurus.io/docs/create-doc
- For guidance on writing and updating Pages, see: https://docusaurus.io/docs/creating-pages

**Comment by riverma** [comment]
@sjlewis-jpl - I've made a bunch of updates to the table to account from David's requested changes. Please review and take it forward.

**Comment by sjlewis-jpl** [comment]
Merging this PR to let the published webpage be updated with the changes here.

**Pull request merged**
